domain_path: C:\Users\BaranidharanKaruppus\Projects\Vitis\IPC\ipc_platform\export\ipc_platform\sw\standalone_psu_cortexr5_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
